1254 Added the changes for common automation framework to accept semvar
nexient-llc/common-automation-framework pull request #2
Opened 2023-10-26 17:45 UTC by saathvika8

2023-10-26 20:31 UTC, cmf-nttdata requested changes

2023-10-26 20:31 UTC, cmf-nttdata commented on manifests/containers/aws/build_agents/shared_service/terraform/manifest/manifest.xml
I think you're missing another entry at line 38.

2023-10-26 20:31 UTC, cmf-nttdata commented on manifests/python/manifest/manifest.xml
Missing another entry on line 9.

2023-10-26 20:31 UTC, cmf-nttdata commented on manifests/containers/aws/build_agents/shared_service/terraform/manifest/manifest.xml
> +  <project name="caf-components-container" path="components/container" remote="launch-dso-platform" revision="refs/tags/0.1.0" dso_override_attribute_revision='${CONTAINER_VER}'>
If we are going to add our own custom properties, the repo tool suggests that we begin the name with x-* as this is reserved for custom names. See here - https://gerrit.googlesource.com/git-repo/+/HEAD/docs/manifest-format.md#Element-project

I also think maybe the name is a little long? Maybe something like `x-override-revision` ?

Also, I'm not sure this even needed yet? Are we doing anything with these variables?

2023-10-26 20:53 UTC, chris-taylor-ntt commented on manifests/containers/aws/build_agents/shared_service/terraform/manifest/manifest.xml
> +  <project name="caf-components-container" path="components/container" remote="launch-dso-platform" revision="refs/tags/0.1.0" dso_override_attribute_revision='${CONTAINER_VER}'>
Looks like this was a customization we did to the git-repo tool:

https://github.com/nexient-llc/git-repo/blob/main/subcmds/envsubst.py#L134-L146

Have we tested this behavior with these replacement vars set to empty strings, or using `unset` to remove them entirely? I'm concerned that this has the possibility of overlaying a good value with an empty string.

2023-10-26 21:07 UTC, chris-taylor-ntt commented on templates/seed_makefile
> +REPO_MANIFESTS_VER ?= update
This doesn't appear to be a valid branch in that repository.

2023-10-27 13:42 UTC, saathvika8 commented on manifests/containers/aws/build_agents/shared_service/terraform/manifest/manifest.xml
> +  <project name="caf-components-container" path="components/container" remote="launch-dso-platform" revision="refs/tags/0.1.0" dso_override_attribute_revision='${CONTAINER_VER}'>
Yeah Chris, I have tested it without and with providing the dso_override_attribute_revision and if the value is not provided it simply keep the revision and if we want to update it to the override revision value , adding it to the Makefile will update it.

2023-10-27 18:00 UTC, cmf-nttdata approved these changes

2023-11-07 17:09 UTC, merged